image: gitpod/workspace-dotnet-vnc
tasks:
  - init: csc src/App.cs -r:System.Windows.Forms.dll
    command: mono App.exe
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==
